### ISSUE TITLE
"ReferenceError: Headers is not defined" during "yarn ingest"

### ISSUE THREAD

**Issue by conroywhitney** [sullivan-sean/chat-langchainjs#14]
Hey -- thanks again for your work on this project. I'm so stoked it exists 😁 

I ran into an error while running `yarn ingest` on a new clone. It seems to be due to a change in `langchainjs` earlier today.

I posted an issue over there and will update here when I hear back: https://github.com/hwchase17/langchainjs/issues/159

In the meantime, I was able to roll back to `"langchain": "0.0.12"` version and `yarn ingest` worked.

**Comment by nfcampos** [comment]
@conroywhitney I replied on the langchainjs issue

**Comment by conroywhitney** [comment]
Thank you!

You're right -- since I was on Node 16, using `NODE_OPTIONS='--experimental-fetch' yarn ingest` fixed the issue.
