### ISSUE TITLE
How do you configure the specific OpenAI model the app uses?

### ISSUE THREAD

**Issue by jackson-sandland** [sullivan-sean/chat-langchainjs#9]
Title says it all.
I see a lot of references to `text-davinci-002` in the generated `docstore.json` file so it appears this is the model being used but I don't see any references to that model in the repo. 
If I'd like to use a different model, how would I set that up?

**Comment by RajSunner** [comment]
Hi, try updating the `pages/api/util.ts` file and include `{ modelName :  "model-you-want" }` as an additional param where `new OpenAI(...)` is used, which is twice in this case.
